import type { Metadata } from "next"
import "./globals.css"

import { GeistMono } from "geist/font/mono"

import { DarkModeProvider } from "@/providers/dark-mode-provider"
import { AIChatProvider } from "@/providers/chat-provider"
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AIChatProvider>
        <body className={`antialiased ${GeistMono.className}`}>
          <DarkModeProvider
            attribute="class"
            defaultTheme="systeml"
            enableSystem
            disableTransitionOnChange
          >
            <main>{children}</main>
            <Toaster
              toastOptions={{ style: { borderRadius: "var(--radius-md)" } }}
            />
          </DarkModeProvider>
        </body>
      </AIChatProvider>
    </html>
  )
}
